<style>
.msgbod{
	display: inline-block;
    position: relative;
    top: 0;
    bottom: 0;
    left: 20%;
    right: 20%;
    width: 750px;
    height: 120px;
    margin: auto;
}
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}
.page-title-wrapper
{
    text-align: center;
}

/*tr:nth-child(even) {
    background-color: #dddddd;
}*/
</style>

<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<div class="checkout-success hidden-xs">
    <h3 style="text-align: center;">We Have Received Your Payment Successfully !</h3>
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
           <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
        <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $this->getUrl('/') ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>


    </div>


</div>
